<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite name="tests.UsersTestCase-20220214134805" tests="10" file="tests.py" time="0.006" timestamp="2022-02-14T13:48:05" failures="1" errors="0" skipped="0">
		<testcase classname="tests.UsersTestCase" name="test_task10_make_migrations" time="0.002" timestamp="2022-02-14T13:48:05" file="module2/tests.py" line="179"/>
		<testcase classname="tests.UsersTestCase" name="test_task1_createapp" time="0.000" timestamp="2022-02-14T13:48:05" file="module2/tests.py" line="7"/>
		<testcase classname="tests.UsersTestCase" name="test_task2_add_settings" time="0.000" timestamp="2022-02-14T13:48:05" file="module2/tests.py" line="15"/>
		<testcase classname="tests.UsersTestCase" name="test_task3_add_template" time="0.000" timestamp="2022-02-14T13:48:05" file="module2/tests.py" line="18"/>
		<testcase classname="tests.UsersTestCase" name="test_task4_create_model" time="0.000" timestamp="2022-02-14T13:48:05" file="module2/tests.py" line="22"/>
		<testcase classname="tests.UsersTestCase" name="test_task6_add_settings" time="0.000" timestamp="2022-02-14T13:48:05" file="module2/tests.py" line="73"/>
		<testcase classname="tests.UsersTestCase" name="test_task7_setup_urls" time="0.001" timestamp="2022-02-14T13:48:05" file="module2/tests.py" line="78"/>
		<testcase classname="tests.UsersTestCase" name="test_task8_redirect_routes" time="0.001" timestamp="2022-02-14T13:48:05" file="module2/tests.py" line="143">
			<!--In `blogproj/urls.py`, add `path('accounts/', include('users.urls')),` 
        as the first entry in the `urlpatterns` array.-->
		</testcase>
		<testcase classname="tests.UsersTestCase" name="test_task9_update_site_templates" time="0.000" timestamp="2022-02-14T13:48:05" file="module2/tests.py" line="169"/>
		<testcase classname="tests.UsersTestCase" name="test_task5_register_admin" time="0.001" timestamp="2022-02-14T13:48:05" file="module2/tests.py" line="40">
			<!--
In order to have access to this model in the admin, we need to register it in `admin.py`.  Letâ€™s do the following:
`from django.contrib.auth.admin import UserAdmin`
`from .models import User`
Call `admin.site.register()` with `User` and `UserAdmin` as parameters.-->
			<failure type="AssertionError" message="Did you import `UserAdmin`?"><![CDATA[Traceback (most recent call last):
  File "/Users/HarryWatson/Dropbox/Coding/python-django-models-authentication/module2/tests.py", line 69, in test_task5_register_admin
    self.assertTrue(import_user_admin_found, msg="Did you import `UserAdmin`?")
  File "/Users/HarryWatson/Dropbox/Coding/python-django-models-authentication/support/SimplerTestCase.py", line 12, in assertTrue
    self.fail(msg or (str(expr) + "is not True"))
AssertionError: Did you import `UserAdmin`?
]]></failure>
		</testcase>
	</testsuite>
</testsuites>
